import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function seed() {
  const email = "system@profal.am";
  const name = "system";

  // cleanup the existing database
  await prisma.user.delete({ where: { email } }).catch(() => {
    // no worries if it doesn't exist yet
  });

  const hashedPassword = await bcrypt.hash("systempass", 10);

  const user = await prisma.user.create({
    data: {
      email,
      name,
      password: {
        create: {
          hash: hashedPassword,
        },
      },
    },
  });

  await prisma.note.create({
    data: {
      title: "My first note",
      body: "Hello, world!",
      userId: user.id,
    },
  });

  await prisma.note.create({
    data: {
      title: "My second note",
      body: "Hello, world!",
      userId: user.id,
    },
  });

  await prisma.reference.createMany({
    data: [
      { id: '3639ea07-960d-4118-8952-5f7835163997', name: "Butyl" },
      { id: 'e9006429-0f01-41ae-b269-6571ef0c2b0c', name: "Assembly seal" },
      { id: '2e91857e-f40b-4cb6-b0e7-c0bb2b856cd6', name: "System renovation" },
      { id: 'f6120b3c-aae9-4de1-b1a6-226aae37d8db', name: "Balanced" },
      { id: '47b675cb-6f30-45ff-9de7-b00f50632af5', name: "Article" },
      { id: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1', name: "Spacer" },
      { id: '711234e8-e76f-4ae6-adb5-6d0d3316c5de', name: "Gergian Bar" },
      { id: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e', name: "Sealent" },
      { id: '26003f44-87f6-4567-8208-95a3c68d414c', name: "Glass product" },
      { id: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf', name: "Insulatin glazing" },
      { id: '3ce7069b-9ca6-4e38-b369-04652e5a6f7c', name: "Desiccant" },
      { id: 'c5620ada-6cd9-4103-8e4b-41434501384b', name: "Filling gas" },
      { id: '6c91051e-2f0e-4893-bca1-c68939973128', name: "Measurement equipment" },
      { id: 'b6a0ace8-eb48-4380-b388-ce634012cbc0', name: "Equipment test" },
      { id: '305111ea-b429-4539-8b2c-fbd2da9cffa4', name: "Claim" },
    ],
  })

  await prisma.article.createMany({
    data: [
      { id: 'b37af5c9-4f3a-4676-aa90-e2f03925aba7', name: "Glazing design" },
      { id: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6', name: "Glazing identification" },
      { id: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26', name: "Component reception" },
      { id: '24b9969c-b439-4fdf-b98d-b30c11b53a13', name: "Article file manufacturing quality" },
      { id: '396671b8-664c-4409-9705-c2819752fdd4', name: "Finished product quality" },
      { id: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41', name: "Finished product quality" },
      { id: '91707178-99e2-4585-b45c-a9fc9e253b21', name: "After sales service" },
    ]
  })

  await prisma.todo.createMany({
    data: [
      {
        remark: "igr 10301",
        referenceId: '3639ea07-960d-4118-8952-5f7835163997',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of the butyl deliveries",
        definition: "Visual",
        method: "Per batch",
        location: "Receiving",
        criteria: "Compliance with the order and good condition of packaging",
        record: "Recording and classification of conformity sheets (after content verification)",
        comments: "Conformity sheets signed or electronic document renamed and archived in a dedicated file",
        userId: user.id
      },
      {
        remark: "igr 10302",
        referenceId: '3639ea07-960d-4118-8952-5f7835163997',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Butyl deliveries not registered at CEKAL",
        definition: "Performance of the tests on butyl sealants specified in chapter 7",
        userId: user.id
      },
      {
        remark: "igr 105je01",
        referenceId: '3639ea07-960d-4118-8952-5f7835163997',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Continuity of the butyl",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "No interruption",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 105je02",
        referenceId: '3639ea07-960d-4118-8952-5f7835163997',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Height of butyl on 2 surfaces of glazing",
        definition: "Measurement",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "Minimum height : 2.5 mm. For trimmed coating, min. contact zone between butyl and trimmed zone= 2.5mm",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 101ja01",
        referenceId: 'e9006429-0f01-41ae-b269-6571ef0c2b0c',
        articleId: 'b37af5c9-4f3a-4676-aa90-e2f03925aba7',
        title: "Stress in highly loaded sealants",
        definition: "Calculation See Pvi 013js01",
        method: "case by case",
        location: "Project",
        criteria: "Compliance with thresholds specified in pvi 012cr12",
        record: "Design note or nomograph",
        comments: "Thick glass-glaz. w/dim out of DTU-with colored glass- screenprinted-installed at high alt.- 2 sides exposed sealant-in structural glazing- point-fixed glaz. (see ch.6)",
        userId: user.id
      },
      {
        remark: "igr 101ja02",
        referenceId: 'e9006429-0f01-41ae-b269-6571ef0c2b0c',
        articleId: 'b37af5c9-4f3a-4676-aa90-e2f03925aba7',
        title: "Limit temperature for glazing sealants",
        definition: "Calculation\nSee Pvi 013js01",
        method: "case by case",
        location: "Project",
        criteria: "Compliance with thresholds specified in pvi 013js01",
        record: "Design note or nomograph",
        comments: "Glazing - with colored glass - screenprinted (see ch. 6)",
        userId: user.id
      },
      {
        remark: "igr 105ja01",
        referenceId: 'e9006429-0f01-41ae-b269-6571ef0c2b0c',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Good contact between sealant/butyl on main portion",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "No filament",
        record: "Recording",
        comments: "Defects submitted to judgment of MVB",
        userId: user.id
      },
      {
        remark: "igr 105ja02",
        referenceId: 'e9006429-0f01-41ae-b269-6571ef0c2b0c',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Good contact between sealant/butyl in the corners",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "No bubbles or missing product",
        record: "Recording",
        comments: "Defects submitted to judgment of MVB",
        userId: user.id
      },
      {
        remark: "igr 105ja03",
        referenceId: 'e9006429-0f01-41ae-b269-6571ef0c2b0c',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Good contact between seals and 9s",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "No interruption in contact",
        record: "Recording",
        comments: "Defects submitted to judgment of MVB",
        userId: user.id
      },
      {
        remark: "igr 103sr01",
        referenceId: '2e91857e-f40b-4cb6-b0e7-c0bb2b856cd6',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of deliveries of renovation systems",
        definition: "Visual",
        method: "per batch",
        location: "Receiving",
        criteria: "Compliance with the order and good condition of packaging",
        record: "Recording and classification of conformity sheets (after content verification)",
        comments: "Conformity sheets signed or electronic document renamed and archived in a dedicated nfile",
        userId: user.id
      },
      {
        remark: "igr 103sr11",
        referenceId: '2e91857e-f40b-4cb6-b0e7-c0bb2b856cd6',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of deliveries of\nprimer",
        definition: "Visual",
        method: "per batch",
        location: "Receiving",
        criteria: "Compliance with the\norder, good condition\nof packaging, expiry\ndate",
        record: "Recording and\nclassification of\nconformity sheets\n(after content\nverification)",
        comments: "Conformity sheets signed or\nelectronic document renamed\nand archived in a dedicated\nfile",
        userId: user.id
      },
      {
        remark: "igr 103sr21",
        referenceId: '2e91857e-f40b-4cb6-b0e7-c0bb2b856cd6',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of deliveries of mastic sealant",
        definition: "Visual",
        method: "per batch",
        location: "Receiving",
        criteria: "Compliance with the order, good condition of packaging, expiry date",
        record: "Recording and classification of conformity sheets (after content verification)",
        comments: "Conformity sheets signed or electronic document renamed and archived in a dedicated file",
        userId: user.id
      },
      {
        remark: "igr 104sr01",
        referenceId: '2e91857e-f40b-4cb6-b0e7-c0bb2b856cd6',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Adhesion-cohesion of renovation profile/primer/mastic sealant",
        definition: "Peeling test as specified in the Igr 123sr03",
        method: "For each batch",
        location: "Receiving and/or manufacturing",
        criteria: "No adhesive breakage breakage at least 90% cohesive",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 105sr01",
        referenceId: '2e91857e-f40b-4cb6-b0e7-c0bb2b856cd6',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Good assembly of the profiles at the corners",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished products",
        criteria: "No opening considered unacceptable",
        userId: user.id
      },
      {
        remark: "igr 105eq01",
        referenceId: 'f6120b3c-aae9-4de1-b1a6-226aae37d8db',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Verification of the process of pre-balancing",
        definition: "Control of the presence of a bending (of the glass)",
        method: "At least 1 glazing per production day",
        location: "Finished products",
        record: "Recording",
        comments: "Wait at least 10min after resealing the glazing",
        userId: user.id
      },
      {
        remark: "igr 105eq02",
        referenceId: 'f6120b3c-aae9-4de1-b1a6-226aae37d8db',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Gas filling rate after pre- balancing",
        definition: "Measurement with a checked non destructive device, min. 2h after glazing pre-balancing",
        method: "At least 1 glazing per production day",
        location: "Finished products",
        criteria: "According to the certification level (85 or 90 or 95%)",
        record: "Recording",
        comments: "See also Igr 104gz01-02-03",
        userId: user.id
      },
      {
        remark: "igr 10401",
        referenceId: '47b675cb-6f30-45ff-9de7-b00f50632af5',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Continuity of the butyl bead",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing and/or finished products",
        criteria: "No interruption",
        userId: user.id
      },
      {
        remark: "igr 10402",
        referenceId: '47b675cb-6f30-45ff-9de7-b00f50632af5',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "No defects at the surface of the bead",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing and/or finished products",
        criteria: "No bubbles or imprint traces",
        userId: user.id
      },
      {
        remark: "igr 10403",
        referenceId: '47b675cb-6f30-45ff-9de7-b00f50632af5',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Position of the bead on the spacer",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing and/or finished products",
        criteria: "Correct centering",
        userId: user.id
      },
      {
        remark: "igr 10404",
        referenceId: '47b675cb-6f30-45ff-9de7-b00f50632af5',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Regularity of the butyl bead on the 2 sides of the spacer",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing and/or finished products",
        criteria: "No irregularities",
        userId: user.id
      },
      {
        remark: "igr 10405",
        referenceId: '47b675cb-6f30-45ff-9de7-b00f50632af5',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Extrusion temperature of the butyl",
        definition: "Reading the thermometer indicators",
        method: "Permanent instruction",
        location: "Manufacturing",
        criteria: "Conformity to supplier sheet or process",
        userId: user.id
      },
      {
        remark: "igr 10406",
        referenceId: '47b675cb-6f30-45ff-9de7-b00f50632af5',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Weight of the extruded butyl bead",
        definition: "Weighing",
        method: "Once per shift for each butyl machine",
        location: "Manufacturing",
        criteria: "Minimum 2.5 g/ml per surface",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 103es01",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of deliveries of spacers registered at CEKAL",
        definition: "Visual",
        method: "per batch",
        location: "Receiving",
        criteria: "Compliance with the order and good condition of packaging",
        record: "Recording and classification of conformity sheets (after content verification)",
        comments: "Conformity sheets signed or electronic document renamed and archived in a dedicated file",
        userId: user.id
      },
      {
        remark: "igr 103es02",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Deliveries of spacers not registered at CEKAL",
        definition: "Performance of tests on spacers specified in chapter 7",
        userId: user.id
      },
      {
        remark: "igr 103es03",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Pre-marking of spacers",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Receiving and/or manufacturing",
        criteria: "Compliance with GTR marking rules and with authorizations",
        userId: user.id
      },
      {
        remark: "igr 103es04",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Straightness, twisting of profiles",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Receiving and/or manufacturing",
        criteria: "No visible anomalies",
        userId: user.id
      },
      {
        remark: "igr 103es06",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Tightness of profile weld (when the weld is in contact with the sealant). (For metal spacer)",
        definition: "Visual, on 2 pieces of profile per batch received",
        method: "Use of penetrating liquid",
        location: "Receiving and/or manufacturing",
        criteria: "No tightness defects",
        record: "Recording or conformity sheet including the control of this tightness",
        comments: "For spacers not registered or if this control doesn't appear on conformity certificate",
        userId: user.id
      },
      {
        remark: "igr 103es11",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Verification of the drill holes on the spacers drilled on site",
        definition: "Blowing air or water flow",
        method: "per delivery",
        location: "Receiving and/or manufacturing",
        criteria: "Presence of the holes and/or air flow or water flow",
        userId: user.id
      },
      {
        remark: "igr 103es21",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of corner keys and straight connectors",
        definition: "Visual",
        method: "per delivery",
        location: "Receiving and/or manufacturing",
        criteria: "Compliance with the order and good condition of packaging",
        userId: user.id
      },
      {
        remark: "igr 103es22",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Cleanliness of  corner keys and straight connectors",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Receiving and/or manufacturing",
        criteria: "Absence of dust",
        comments: "Storage conditions to be monitored",
        userId: user.id
      },
      {
        remark: "igr 103es31",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Deformability of foldable corner keys",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Receiving and/or manufacturing",
        criteria: "Good hold of  corners keys in place",
        userId: user.id
      },
      {
        remark: "igr 104es00",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Identification of « Warm- edge » spacers (for synthetic material spacers)",
        definition: "Measures ensuring the identification of such spacers installed in each glazing",
        method: "Permanent instruction",
        location: "Finished products",
        criteria: "Distinction of each spacer with improved thermal purpose",
        record: "Marking on the spacer (type, commercial reference)",
        comments: "If no marking on the spacer, a traceability system is required.",
        userId: user.id
      },
      {
        remark: "igr 104es01",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Cleanliness of frames",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing",
        criteria: "Prohibition to put on the floor. Absence of dust.",
        comments: "Compulsory degreasing if delivered Georgian bars are fixed on frames",
        userId: user.id
      },
      {
        remark: "igr 104es02",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Finishing of frame corners",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing",
        criteria: "No major defects",
        userId: user.id
      },
      {
        remark: "igr 104es03",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Dimensions and straightness of metal frames",
        definition: "Measurement of width x height",
        method: "1 frame/shift and per equipment",
        location: "Manufacturing",
        criteria: "Compliance with the tolerances specified in the process",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 104es04",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Dimensions and straightness of synthetic material frames",
        definition: "Measurement of width x height",
        method: "1 frame/shift and per equipment",
        location: "Manufacturing",
        criteria: "Compliance with the tolerances specified in the process",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 104es05",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Max. waiting time of dessicant inside the tubular spacer frame before insulating glazing assembly",
        definition: "Measurement of the time",
        method: "Permanent instruction",
        location: "Manufacturing workshop with relative humidity ≤ 60%RH",
        criteria: "8 hours max.",
        record: "Justification expected if the 8 hours are exceeded or if RH > 60%",
        comments: "Expected justification: Successive weighing of the frame until obtaining water absorption of 1% max.",
        userId: user.id
      },
      {
        remark: "igr 104es11",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Corner key strength",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing",
        criteria: "Good strength of corner keys",
        userId: user.id
      },
      {
        remark: "igr 104es12",
        referenceId: '4bf39bdc-2f37-4571-b415-1bf5a0d24ac1',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Good application of the butyl in the corners",
        definition: "Visual on the butyl- coated frame, before assembling",
        method: "Permanent instruction",
        location: "Manufacturing",
        criteria: "Continuity of the butyl in the corners",
        comments: "Corners with corner keys",
        userId: user.id
      },
      {
        remark: "igr 103sc01",
        referenceId: '711234e8-e76f-4ae6-adb5-6d0d3316c5de',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of Georgian bar deliveries (profiles)",
        definition: "Visual appearance",
        method: "2 profiles per delivery",
        location: "Receiving",
        criteria: "Compliance with the order (including the film reference if appropriate) and good condition of packaging",
        userId: user.id
      },
      {
        remark: "igr 103sc02",
        referenceId: '711234e8-e76f-4ae6-adb5-6d0d3316c5de',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of deliveries of frames with Georgian bars",
        definition: "Visual",
        method: "2 frames per delivery",
        location: "Receiving",
        criteria: "Compliance with the order (Including the film ref.if appropriate,  + ref. and type of the spacer) and good condition of packaging",
        record: "Recording and classification of conformity sheets(after content verification) + correlation  delta T/initial water content",
        userId: user.id
      },
      {
        remark: "igr 103el01",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of deliveries of elastomer sealant",
        definition: "Visual",
        method: "Per batch",
        location: "Receiving",
        criteria: "Compliance with the order, good condition of packaging, expiry date",
        record: "Recording and classification of conformity sheets (after content verification)",
        comments: "Conformity sheets signed or electronic document renamed and archived in a dedicated file",
        userId: user.id
      },
      {
        remark: "igr 103el02",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Deliveries of elastomer sealant not registered at CEKAL",
        definition: "Performance of tests on elastomer sealants specified in chapter 7",
        userId: user.id
      },
      {
        remark: "igr 103el03",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Adhesiveness of elastomer/glass bond",
        definition: "Butterfly test or adherence test in initial state with tensile specimen as per EN1279-6, ann. D up tobreakage",
        method: "1 specimen per batch at receiving or start of manufacturing (additional spec.if pbm)",
        location: "Receiving or start of manufacturing",
        criteria: "No adhesive Adhesiveness of breakage",
        record: "Recording",
        comments: "Mixed specimen possible. For ex. at 1 day, then 3 or 7 days if necessary (see Igr 123ms02)",
        userId: user.id
      },
      {
        remark: "igr 103el04",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Adhesiveness of the elastomer sealant/metal spacer bond",
        definition: "Butterfly test or adherence test in initial state with tensile specimen as per EN1279-6, ann. D up to breakage",
        method: "1 specimen per batch at start of manufacturing (additional spec.if pbm)",
        location: "Receiving or start of manufacturin",
        criteria: "No adhesive up to breakage",
        record: "Recording",
        comments: "Mixed specimens possible.\nFor ex. at 1 day, then 3 or 7\ndays if necessary (see Igr\n123ms02)",
        userId: user.id
      },
      {
        remark: "igr 103el11",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of deliveries of\nstructural glazing elastomer\nsealant registered at CEKAL",
        method: "per batch",
        location: "Receiving",
        criteria: "Compliance with the\norder, good condition\nof packaging, batch\nNo., expiry date",
        record: "Recording and\nclassification of\nconformity sheets\n(after content\nverification)",
        comments: "Conformity sheets signed or\nelectronic document renamed\nand archived in a dedicated\nfile",
        userId: user.id
      },
      {
        remark: "igr 104el01",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Expiry date",
        definition: "Visual",
        method: "Per container",
        location: "Manufacturing",
        criteria: "No exceeding of the date",
        userId: user.id
      },
      {
        remark: "igr 104el02",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Good filling of the seals",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing and/or finished products",
        criteria: "No bubbles, air filaments, excess material, etc.",
        userId: user.id
      },
      {
        remark: "igr 104el03",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Adhesiveness of elastomer sealant/glass bond",
        definition: "Butterfly test or adherence test in initial state with tensile specimen as per EN 1279-6, ann. F  up to breakage",
        method: "Once per shift and per mixing head",
        location: "Manufacturing",
        criteria: "No adhesive breakage",
        record: "Recording",
        comments: "Mixed specimen possible. For ex.at 1 day, then 3 or 7 days if necessary. (See Igr 123ms02). Perform for each type of spacer.",
        userId: user.id
      },
      {
        remark: "igr 104el04",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Adhesiveness of the elastomer sealant/metal spacer bond",
        definition: "Butterfly test or adherence test in initial state with tensile specimen as per EN 1279-6, ann. F up to breakage",
        method: "Once per shift and per mixing head",
        location: "Manufacturing",
        criteria: "No adhesive breakage",
        record: "Recording",
        comments: "Mixed specimen possible. For ex.at 1 day, then 3 or 7 days if necessary. (See Igr 123ms02). See also Igr 104el05.",
        userId: user.id
      },
      {
        remark: "igr 104el05",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Adhesiveness of the elastomer sealant/synthetic material spacer bond",
        definition: "Butterfly test or adherence test in initial state with tensile specimen as per EN 1279-6, ann. F up to breakage",
        method: "Once per shift and per mixing head",
        location: "Manufacturing",
        criteria: "No adhesive breakage",
        record: "Recording",
        comments: "Mixed specimen possible. For ex.at 1 day, then 3 or 7 days if necessary. (See Igr 123ms02). See also Igr 104el04.",
        userId: user.id
      },
      {
        remark: "igr 104el11",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Shore hardness (mono- compound sealant).",
        definition: "Measurement with durometer",
        method: "Once per container",
        location: "Manufacturing",
        criteria: "Thresholds set by supplier",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 104el21",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Homogenous aspect of sealant",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing",
        criteria: "No visible heterogeneity of color",
        userId: user.id
      },
      {
        remark: "igr 104el22",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Base/hardener ratio (procedure required)",
        definition: "Measurement",
        method: "Once a week per coating equipment",
        location: "Manufacturing",
        criteria: "Thresholds set by supplier",
        record: "Recording",
        comments: "Weighing method or method recommended by machine manufacturer and sealant manufacturer",
        userId: user.id
      },
      {
        remark: "igr 104el23",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Shore hardness (dual compound sealant)",
        definition: "Measurement with durometer",
        method: "Once per shift and per mixing head, once per batch when put into service",
        location: "Manufacturing",
        criteria: "Thresholds set by supplier",
        record: "Recording",
        comments: "For a new batch: perform at start of use, as an acceptance test",
        userId: user.id
      },
      {
        remark: "igr 104el24",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Homogeneity of dual compound sealants",
        definition: "Visual",
        method: "Once per shift and per mixing head",
        location: "Manufacturing",
        criteria: "No visible heterogeneity of color",
        record: "Recording",
        comments: "Keep specimens at least 1 month. Note the batch numbers.",
        userId: user.id
      },
      {
        remark: "igr 104el31",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Temperature and hygrometry of the structural glazing manufacturing shop",
        definition: "Measurement of temp. and hygrometry",
        method: "Once per shift",
        location: "Manufacturing",
        criteria: "According to indications in sealing procedure",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 104el32",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Rinsing solvent for the structural glazing coating equipment",
        definition: "Visual",
        method: "Once a week",
        location: "Manufacturing",
        criteria: "Recording the solvent reference",
        record: "Recording",
        comments: "If a solvent is used",
        userId: user.id
      },
      {
        remark: "igr 104el33",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Base/hardener ratio for structural glazing sealant (procedure required)",
        definition: "Measurement",
        method: "Once per shift per coating equipment",
        location: "Manufacturing",
        criteria: "Thresholds set by supplier",
        record: "Recording",
        comments: "Weighing method or method recommended by machine manufacturer and sealant manufacturer",
        userId: user.id
      },
      {
        remark: "igr 104el34",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Homogeneity of dual compound structural glazing sealants",
        definition: "Visual",
        method: "Once per shift and per coating head, and with each new batch",
        location: "Manufacturing",
        criteria: "No visible heterogeneity of color",
        record: "Recording",
        comments: "Note the batch numbers.",
        userId: user.id
      },
      {
        remark: "igr 104el35",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Adherence tests for structural glazing sealants option 1: [2 H-specimens (glass/glass and spacer/spacer) or 1 mixed specimen] + [1 specimen of peeling]",
        definition: "Measurement of adherence and breakage strength",
        method: "H-shaped specimen once per contract and per batch change. Peeling test once per shift.",
        location: "Manufacturing",
        criteria: "Cohesive breakage>=90% and breakage stress according to the pescription of the sealant supplier",
        record: "Recording of the type of rupture and of strength at breakage",
        comments: "\"H\" specimen in compliance with ETAG 002, tabl. 5 and fig. 6, peeling test according to fig. 19 and 20.",
        userId: user.id
      },
      {
        remark: "igr 104el36",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Adherence tests for structural glazing sealants option 2: [3 H-specimen glass/glass + 3 specimens spacer/spacer] or [3 mixed specimens]",
        definition: "Measurement of adherence and breakage strength",
        method: "Once per shift",
        location: "Manufacturing",
        criteria: "Cohesive breakage\n>=90% and breakage stress according to the pescription of the sealant supplier",
        record: "Recording of the type of rupture and of strength at breakage",
        comments: "\"H\" specimen in compliance with ETAG 002, tabl. 5 and fig. 6.",
        userId: user.id
      },
      {
        remark: "igr 104el37",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Adherence tests for structural glazing sealants option 3: [3 H-specimen glass/glass + 3 specimens spacer/spacer] or [3 mixed specimens]",
        definition: "Measurement of adherence and breakage strength",
        method: "Once per shift",
        location: "Manufacturing",
        criteria: "Cohesive breakage\n>=90% and breakage stress according to the pescription of the sealant supplier",
        record: "Recording of the type of rupture and of strength at breakage",
        comments: "\"H\" specimen in compliance with NF EN 1279-6, ann. D.3.1",
        userId: user.id
      },
      {
        remark: "igr 105js01",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Homogeneity of sealants",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "No visible heterogeneity of color",
        record: "Recording",
        comments: "Defects submitted to judgment of MVB",
        userId: user.id
      },
      {
        remark: "igr 105js02",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Good filling by the sealants",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "No major empty spot on the edges",
        record: "Recording",
        comments: "Defects submitted to judgment of MVB",
        userId: user.id
      },
      {
        remark: "igr 105js03",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Sealants are in good flush position with respect to glazing edges",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "No major outcrops or recesses",
        record: "Recording",
        comments: "Defects submitted to judgment of MVB",
        userId: user.id
      },
      {
        remark: "igr 105js04",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "No inclusion of air or gas",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "No bubbles",
        record: "Recording",
        comments: "Defects submitted to judgment of MVB",
        userId: user.id
      },
      {
        remark: "igr 105js05",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Residue of silicone on face 2 (double) or 4 (triple) of IG to be clamped without reception profile, on the part of the glass which goes beyond the sealant",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished products",
        criteria: "No translparency",
        userId: user.id
      },
      {
        remark: "igr 105js06",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Thickness of the silicon film on side 3 (double) or 5 (triple), of IG to be clamped without reception profile, on the part of the glass which goes beyond the sealant",
        definition: "Measurement",
        method: "1 glazing per line per shift",
        location: "Finished products\nIn the middle of the 2 sides with dedicated space",
        criteria: "Maximum 1mm",
        record: "Recording",
        comments: "Difference between the total nominal value and the measured value",
        userId: user.id
      },
      {
        remark: "igr 105js07",
        referenceId: '8037e881-0e3b-42a7-b63d-1ce02e83dd2e',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Dedicated space for the insertion of the clamp without reception",
        definition: "Measurement",
        method: "1 glazing per line per shift",
        location: "Finished products In the middle of the 2 sides with dedicated space",
        criteria: "Sufficient space as defined in technical sheet  n°57 SNFA/COPREC",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 101pv01",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: 'b37af5c9-4f3a-4676-aa90-e2f03925aba7',
        title: "Stress on highly loaded glazing panes",
        definition: "Calculation\nSee Pvi 013js01",
        method: "case by case",
        location: "Project",
        criteria: "Compliance with thresholds specified in pvi 012cr12 and the related Avis Technique.",
        record: "Design note",
        comments: "Glazing with 2 sides exposed sealant-structural glazing - point-fixed glazing - with colored glass - screenprinted (see ch.6)",
        userId: user.id
      },
      {
        remark: "igr 102pv01",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Marking of heat treated panes",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished product",
        criteria: "Presence of marking",
        userId: user.id
      },
      {
        remark: "igr 102pv02",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Marking of surfaces coated with non-visible layers",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished product",
        criteria: "Presence of an indication\nSee pvi 014et01",
        comments: "Coatings that are slightly emissive, self-cleaning, etc.",
        userId: user.id
      },
      {
        remark: "igr 103pv01",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of deliveries of 9s including the identification of coated 9s",
        definition: "Visual",
        method: "Per delivery",
        location: "Receiving",
        criteria: "Compliance with the order and good condition of packaging",
        comments: "Declaration of performance for CE marking",
        userId: user.id
      },
      {
        remark: "igr 104pv01",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Absence of defects in glass thickness",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing and/or finished products",
        criteria: "NF EN 572",
        userId: user.id
      },
      {
        remark: "igr 104pv02",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Absence of defects on the surface",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing and/or finished products",
        criteria: "NF EN 572",
        userId: user.id
      },
      {
        remark: "igr 104pv03",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Absence of cutting defects, good edge condition",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing and/or finished products",
        userId: user.id
      },
      {
        remark: "igr 104pv04",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Identification of low emissivity coated glasses and  laminated safety glass.",
        definition: "Measures ensuring the identification of such glassesinstalled in each glazing",
        method: "Permanent instruction",
        location: "Finished products",
        criteria: "Distinction of coated glasses and laminated glass types",
        record: "Marking or documentary system",
        comments: "To be able to find the batch number and the glass supplier",
        userId: user.id
      },
      {
        remark: "igr 104pv11",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Edge bevel of beveled 9s",
        definition: "Measurement",
        method: "Once per shift/line",
        location: "Manufacturing and/or finished products",
        criteria: "<1mm if thickn.<8mm, <2mm if thickn.>8mm",
        comments: "See Igr 055bs01",
        userId: user.id
      },
      {
        remark: "igr 104pv12",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Residual thickness of the bevel on beveled 9s",
        definition: "Measurement",
        method: "At each change of shift",
        location: "Manufacturing and/or finished products",
        criteria: "Minimum thickness of glass: 3mm and bevel thickn. <=half-thickn. of glass component",
        userId: user.id
      },
      {
        remark: "igr 104pv21",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Regularity of edge trimming",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing",
        criteria: "Regular removal of the layer in compliance with the procedure",
        record: "Recording if specified in the procedure",
        userId: user.id
      },
      {
        remark: "igr 104pv22",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Height of peripheral margin",
        definition: "Measurement",
        method: "At each change of shift",
        location: "Manufacturing",
        criteria: "Height of margin specified",
        comments: "applies to sandblasting and acid etching, coated, screenprinted glazing",
        userId: user.id
      },
      {
        remark: "igr 104pv311",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Conductivity of rinse water",
        definition: "Measurement of the conductivity of the rinse water (or resistivity)",
        method: "Once/day",
        location: "Closest to the water supply of the rinsing ramp",
        criteria: "Conductivity <30 µS. cm-1  or specif.of the coated glass supplier or of DTA if inferior",
        record: "Recording",
        comments: "Absence of detergent",
        userId: user.id
      },
      {
        remark: "igr 104pv313",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Temperature of washing water",
        definition: "Measurement of the washing water temperature",
        method: "Once/day",
        location: "In the washing water supply tank",
        criteria: "Temperature ≥35°C",
        record: "Recording of the measured values",
        userId: user.id
      },
      {
        remark: "igr 104pv32",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Cleanliness of surfaces after washing",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing",
        criteria: "No deposits that could hinder adhesiveness of assembly products",
        userId: user.id
      },
      {
        remark: "igr 104pv33",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Quality of drying",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Manufacturing",
        criteria: "No residual drop of water",
        userId: user.id
      },
      {
        remark: "igr 105pv01",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Cutting quality of edges",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "Prevailing standards",
        record: "Recording",
        comments: "Composition, dimensions",
        userId: user.id
      },
      {
        remark: "igr 105pv03",
        referenceId: '26003f44-87f6-4567-8208-95a3c68d414c',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Cleanliness of 9s",
        definition: "Visual",
        method: "1 glazing per line per shift",
        location: "Finished products",
        criteria: "Prevailing standards",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 102vi01",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Marking with the commercial name or name of center",
        definition: "Visual",
        method: "Permanent instruction",
        location: "When ordered and/or during manufacture",
        criteria: "See Igr 011mq01",
        userId: user.id
      },
      {
        remark: "igr 102vi02",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Marking of manufacturing date",
        definition: "Visual",
        method: "Permanent instruction",
        location: "When ordered and/or during manufacture",
        criteria: "At min., the semester (s1 or s2) and yr. or refer to Igr 011mq01",
        userId: user.id
      },
      {
        remark: "igr 102vi03",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "CEKAL marking with the center No.",
        definition: "Visual",
        method: "Permanent instruction",
        location: "When ordered and/or during manufacture",
        criteria: "Conformity with resp to authorizations and certificates\nSee Igr 011mq01",
        userId: user.id
      },
      {
        remark: "igr 102vi11",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Marking of renovation glazing",
        definition: "Visual",
        method: "Permanent instruction",
        location: "When ordered and/or during manufacture",
        criteria: "Letter R added to the marking sequence See Igr 011mq01 and 02",
        comments: "R marking indicates \"renovation glazing\"",
        userId: user.id
      },
      {
        remark: "igr 102vi12",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Marking of glazing with seals exposed to sunlight",
        definition: "Visual",
        method: "Permanent instruction",
        location: "When ordered and/or during manufacture",
        criteria: "Letter B added to the marking sequence See Igr 011mq01",
        comments: "B marking indicates resistance to sunlight",
        userId: user.id
      },
      {
        remark: "igr 102vi13",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Marking of structural glazing",
        definition: "Visual",
        method: "Permanent instruction",
        location: "When ordered and/or during manufacture",
        criteria: "Letter C added to the marking sequence See Igr 011mq01",
        comments: "C marking indicates resistance to sunlight and verification of stress",
        userId: user.id
      },
      {
        remark: "igr 102vi31",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Marking of the reference angle for glazing weighing over 100 kg",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished product",
        criteria: "Presence of an indication See Igr 011mq03",
        userId: user.id
      },
      {
        remark: "igr 102vi32",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Marking of the reference angle for structural glazing",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished product",
        criteria: "Presence of an indication See Igr 011mq03",
        userId: user.id
      },
      {
        remark: "igr 102vi33",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Labeling of the installation altitude for pre-balanced glazing",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished product",
        criteria: "Presence of an indication See Igr 011mq03",
        userId: user.id
      },
      {
        remark: "igr 102vi34",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: 'd9564e20-9f09-49ff-9cef-3a1a37955ec6',
        title: "Labeling of the breather position",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished product",
        criteria: "Presence of an indication See Igr 011mq03",
        userId: user.id
      },
      {
        remark: "igr 104vi01",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Protection of glazing panes from sunlight and bad weather",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished products",
        criteria: "Storage under shelter",
        userId: user.id
      },
      {
        remark: "igr 104vi02",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Storage of glazing panes after manufacturing",
        definition: "Visual",
        method: "Permanent instruction",
        location: "Finished products",
        criteria: "Storage at 90° on stand (between basis and back) to avoid shear stress",
        comments: "Flat storage if possible. Stand with an anti-adhesion system.",
        userId: user.id
      },
      {
        remark: "igr 105vi011",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Resistance to humidity of the assembly system (case of internal laboratory)",
        definition: "Measurement of the dew point OR the humidity index after the oven",
        method: "At least 1 glazing/line/month. At least 1 glazing/type of sealant/month. Alternate spacers from one month to another.",
        location: "Finished products Sample 350x500mm - 4/16/4 with Low-E pos. 3",
        criteria: "T° initial dew point - ≤60°C and after 56 days at 55°C (0;+3) and 95%RH; Index I≤0,050 after 3 weeks at 58°C and 95% RH",
        record: "Recording",
        comments: "This control also applies to the manufacture of glazing installed for renovation. If 1 line  with 2 sealant coatings (automatic and manual) alternate the coating",
        userId: user.id
      },
      {
        remark: "igr 105vi012",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Resistance to humidity of the assembly system (case of external laboratory)",
        definition: "Measurement of  the humidity index after the oven",
        method: "At least 2 glazings per line/6weeks. At least 2 glazings per type of sealant per 6 weeks. (Alternate the spacers).",
        location: "Finished products Sample 350x500mm - 4/16/4 with Low-E pos. 3",
        criteria: "Index I≤0,050 after 3 weeks at 58°C and 95% RH",
        record: "Recording",
        comments: "This control also applies to the manufacture of glazing installed for renovation. If 1 line  with 2 sealant coatings (automatic and manual) alternate the coating",
        userId: user.id
      },
      {
        remark: "igr 105vi02",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Conformity of the total thickness of the glazing and amplitude of thickness variations",
        definition: "Measurement at 5 points (3 corners and middle of 2 sides)",
        method: "1 glazing per line, per shift and per process",
        location: "Finished products",
        criteria: "Processes not covered by Avis Technique: see Pvi 012vr11; otherwise, as per.Avis Technique",
        record: "Recording",
        comments: "Avis Technique for  the processes it covers.",
        userId: user.id
      },
      {
        remark: "igr 105vi03",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Parallelism of surfaces, amplitude of thickness variations",
        definition: "Measurement at 5 points (3 corners + middle of 2 adjacent sides)",
        method: "1 glazing per line, per shift",
        location: "Finished products",
        criteria: "Difference in thickness chosen by the center or specified by the ATECs",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 105vi04",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Dimensional tolerances on width, height, and edge offset",
        definition: "Measurement of the width, height and edge offset",
        method: "1 glazing per line, per shift and per process\n+ 1 glazing per line et per shift for glazing to be clamped, without reception profle",
        location: "Finished products",
        criteria: "Conformity to the Pvi 012vr11",
        record: "Recording",
        comments: "Applies to dimensional control during manufacturing",
        userId: user.id
      },
      {
        remark: "igr 105vi05",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Glazing composition",
        definition: "Visual",
        method: "1 glazing per line, per shift",
        location: "Finished products",
        criteria: "Conformity to the order",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 105vi06",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Glazing marking",
        definition: "Visual",
        method: "1 glazing per line, per shift",
        location: "Finished products",
        criteria: "Conformity to the Pvi 014mq01",
        record: "Recording",
        comments: "If \"CE\" marking: conformity of this marking",
        userId: user.id
      },
      {
        remark: "igr 105vi07",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Height of sealant at the back of the spacer",
        definition: "Visual/Measurement",
        method: "1 glazing per line, per shift",
        location: "Finished products",
        criteria: "3 mm, or as per Atec or DTA; for IG with hot-melt sealant. see Igr 104tf04; for specific IG (bonded, to be clamped) according to calculation",
        record: "Recording",
        comments: "With PMBuxx processes with PS, PU, Sb or Sm: occasionally 2.5 mm",
        userId: user.id
      },
      {
        remark: "igr 105vi08",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Flatness",
        definition: "Visual",
        method: "1 glazing per  line, per shift",
        location: "Finished products",
        criteria: "No visible flatness defect at the time of manufacture",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 105vi09",
        referenceId: 'fadfe793-233d-48af-b5b3-6ac438c2c2cf',
        articleId: '396671b8-664c-4409-9705-c2819752fdd4',
        title: "Condition of glass pane edges",
        definition: "Visual",
        method: "1 glazing per  line, per shift and per process",
        location: "Finished products",
        criteria: "No defects or chipping",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 103ds01",
        referenceId: '3ce7069b-9ca6-4e38-b369-04652e5a6f7c',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of the deliveries of molecular sieves",
        definition: "Visual",
        method: "Per batch",
        location: "Receiving",
        criteria: "Compliance with the order and good condition of packaging",
        record: "Recording and classification of conformity sheets(after content verification) + correlation  delta T/initial water content",
        comments: "Conformity sheets signed or electronic document renamed and archived in a dedicated file",
        userId: user.id
      },
      {
        remark: "igr 103ds02",
        referenceId: '3ce7069b-9ca6-4e38-b369-04652e5a6f7c',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Deliveries of molecular sieves not registered at CEKAL",
        definition: "Performance of tests on desiccants specified in chapter 7",
        userId: user.id
      },
      {
        remark: "igr 104ds01",
        referenceId: '3ce7069b-9ca6-4e38-b369-04652e5a6f7c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Good filling of the metallic spacers with desiccant",
        definition: "Measuring weight or volume",
        method: "Once per shift, per spacer family (PMA, PMI, PMG) and per filling machine",
        location: "Manufacturing",
        criteria: "Complete filling of the sides specified in the process",
        record: "Recording",
        comments: "Vary the widths and references of spacers within the same family (PMA, PMI, PMG)\nSee also Igr 104ds02",
        userId: user.id
      },
      {
        remark: "igr 104ds02",
        referenceId: '3ce7069b-9ca6-4e38-b369-04652e5a6f7c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Good filling of the synthetic material spacers with desiccant",
        definition: "Measuring weight or volume",
        method: "Once per shift, per spacer family (PSF) and per filling machine",
        location: "Manufacturing",
        criteria: "Complete filling of the sides specified in the process",
        record: "Recording",
        comments: "Vary the widths and references of spacers within the same family (PSF)\nSee also Igr 104ds01",
        userId: user.id
      },
      {
        remark: "igr 104ds03",
        referenceId: '3ce7069b-9ca6-4e38-b369-04652e5a6f7c',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Initial water content of the desiccant",
        definition: "Exothermal test",
        method: "Once per shift per filling machine and each time a package is opened",
        location: "Manufacturing",
        criteria: "1,7% when a package is opened 3% when the package has alredy been opened",
        record: "Recording of initial, final temperature and the delta of the temperature",
        comments: "The procedure, the control equipment and the correlation curve\ndelta T/water content are provided by the desiccant manufacturer",
        userId: user.id
      },
      {
        remark: "igr 103gz01",
        referenceId: 'c5620ada-6cd9-4103-8e4b-41434501384b',
        articleId: 'e1b163bd-4cbd-4739-a878-dc8f1827ec26',
        title: "Conformity of gas deliveries",
        definition: "Visual",
        method: "Per delivery",
        location: "Receiving",
        userId: user.id
      },
      {
        remark: "igr 104gz011",
        referenceId: 'c5620ada-6cd9-4103-8e4b-41434501384b',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Filling the space between glazing panes (double glazing with argon gas 85% or krypton gas 85% )",
        definition: "Measurement with checked  oxymeter and/or non destructive equipment minimun 2 hours  after glazing manufacturing",
        method: "1 vol. per shift and filling machine if prod. < 100 v/shift 2 vol. per shift and filling machine if prod. > 100 v/shift",
        location: "Finished products put on the market",
        criteria: "Filling rate 85% (supervision thresholds set for corrective action). No value under 80%",
        record: "Recording of each measurement+average calculation every 1,4 and 12 weeks. Quarterly average=85% (-0;+15)",
        comments: "minimum of 3 vol./24hr if the total prod./ center > 100 v/day. Tandem press =2 filling machines",
        userId: user.id
      },
      {
        remark: "igr 104gz012",
        referenceId: 'c5620ada-6cd9-4103-8e4b-41434501384b',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Filling the space between glazing panes ( triple glazing with argon gas85% or krypton 85%)",
        definition: "Measurement with checked  oxymeter and/or non destructive equipment minimun 2 hours  after glazing manufacturing",
        method: "1 vol. per shift and filling machine if prod. < 100 v/shift 2 vol. per shift and filling machine if prod. > 100 v/shift",
        location: "Sample manufactured according to the used process",
        criteria: "Filling rate 85% (supervision thresholds set for corrective action). No value under 80%",
        record: "Recording of each measurement+average calculation every 1,4\nand 12 weeks. Quarterly average=85% (-0;+15)",
        comments: "minimum of 3 vol./24hr if the total prod./ center > 100 v/day. Tandem press =2 filling machines\nIf manual filling: 1 vol./day",
        userId: user.id
      },
      {
        remark: "igr 104gz02",
        referenceId: 'c5620ada-6cd9-4103-8e4b-41434501384b',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Filling the space between glazing panes (double glazing with argon gas 90%)",
        definition: "Measurement with checked oxymeter and/or  non destructive equipment minimun 2 hours  after glazing manufacturing",
        method: "1 vol. per shift and filling machine if prod. < 100 v/shift 2 vol. per shift and filling machine if prod. > 100 v/shift",
        location: "Finished products put on the market",
        criteria: "Filling rate 90% (supervision thresholds set for corrective action). No value under 85%",
        record: "Recording of each measurement+average calculation every 1,4 and 12 weeks. Quarterly average=90% (-0;+10)",
        comments: "minimum of 3 vol./24hr if the total prod./ center > 100 v/day. Tandem press=2 filling machines",
        userId: user.id
      },
      {
        remark: "igr 104gz03",
        referenceId: 'c5620ada-6cd9-4103-8e4b-41434501384b',
        articleId: '24b9969c-b439-4fdf-b98d-b30c11b53a13',
        title: "Filling the space between glazing panes (double glazing with argon gas 95%)",
        definition: "Measurement with checked oxymeter and/or  non destructive equipment minimun 2 hours  after glazing manufacturing",
        method: "1 vol. per shift and filling machine if prod. < 100 v/shift 2 vol. per shift and filling machine if prod. > 100 v/shift",
        location: "Finished products put on the market",
        criteria: "Filling rate 95% (supervision thresholds set for corrective action).No value under 90%",
        record: "Recording of each measurement+average calculation every 1,4 and 12 weeks. Quarterly average=95% (-0;+5)",
        comments: "minimum of 3 vol./24hr if the total prod./ center > 100 v/day. Tandem press =2 filling machines",
        userId: user.id
      },
      {
        remark: "igr 106em11",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the scales",
        definition: "Comparison with the reference weights",
        method: "Twice a year",
        location: "By the center",
        criteria: "Accepted gap:\n- from 0 to 100g :\n≤ 0.2g\n- from 101 to 1000g :\n≤ 2g",
        record: "Recording",
        comments: "Scale’s accuracy : 10th  of gram.\nVerification performed as specified in the Igr 110em02",
        userId: user.id
      },
      {
        remark: "igr 106em21",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the thickness measurement instrument or caliper",
        definition: "Comparison with class 1 reference gage blocks",
        method: "Twice a year",
        location: "By the center",
        criteria: "Accepted gap:\n≤ 0.1mm",
        record: "Recording",
        comments: "Verification to be performed as specified in the Igr 110em01",
        userId: user.id
      },
      {
        remark: "igr 106em211",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the digital limit stops",
        definition: "Comparison with a reference length rule",
        method: "Twice a year",
        location: "By the center",
        criteria: "Accepted gap:\n≤ 0.5mm",
        record: "Recording",
        comments: "Verification to be performed as specified in the Igr 110em01",
        userId: user.id
      },
      {
        remark: "igr 106em31",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the durometers",
        definition: "Comparison with reference blocks",
        method: "Twice a year",
        location: "By the center",
        criteria: "Accepted gap:  +/- 3 shore(A)",
        record: "Recording",
        comments: "Verification to be performed as specified in the Igr 110em03",
        userId: user.id
      },
      {
        remark: "igr 106em51",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the thermometers positive and negative",
        definition: "Comparison with a reference thermometer",
        method: "Twice a year",
        location: "By the center",
        criteria: "Permissible deviation ≤ 2°C for electro. thermometers ≤ 3°C for liquid-filled or dial thermometers",
        record: "Recording",
        comments: "Verification to be performed as specified in the Igr 110em05",
        userId: user.id
      },
      {
        remark: "igr 106em61",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the oxymeters",
        definition: "Determination of the oxygen content in the air",
        method: "Each time started up",
        location: "By the center",
        criteria: "Equipment recalibrated each time started up",
        record: "/",
        comments: "Equipment to be re-controled in accordance with supplier recommendations",
        userId: user.id
      },
      {
        remark: "igr 106em62",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the non destructive gas 13",
        definition: "Verification by comparison following 3 possible options (see Igr 110em07)",
        method: "Once/month or once/quarter according to the chosen option",
        location: "By the center",
        criteria: "Variation accepted without correction: <1% Variation accepted with correction: ≤ 4%",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 106em81",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the tape measures",
        definition: "Replacement of the tape measures if worn",
        method: "Every year",
        location: "By the center",
        criteria: "Tape measures of class II",
        record: "Recording",
        userId: user.id
      },
      {
        remark: "igr 106em91",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the conductivity meters or resistivity meters",
        definition: "Comparison with a reference solution",
        method: "Twice a year",
        location: "By the center",
        criteria: "Accepted gap ≤ 5 µS/cm",
        record: "Recording",
        comments: "Verification to be performed as specified in the Igr 110em04",
        userId: user.id
      },
      {
        remark: "igr 106ema1",
        referenceId: '6c91051e-2f0e-4893-bca1-c68939973128',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of the traction devices for structural glazing",
        definition: "Calibration",
        method: "Every 2 years (intermittent use)",
        location: "Inspection body",
        criteria: "/",
        record: "Recording",
        comments: "To be calibrated every year in the event of daily use",
        userId: user.id
      },
      {
        remark: "igr 106ee11",
        referenceId: 'b6a0ace8-eb48-4380-b388-ce634012cbc0',
        articleId: 'bf7b632a-f62f-4fd9-b6d6-dcdfe9c70f41',
        title: "Verification of oven temperatures and condition",
        definition: "Reading the thermometer and obs. the presence of water or verif. hygrometry (steam operation)",
        method: "Permanent instruction",
        location: "By the center",
        criteria: "T=55°C (+3,-0)",
        userId: user.id
      },
      {
        remark: "igr 107rc01",
        referenceId: '305111ea-b429-4539-8b2c-fbd2da9cffa4',
        articleId: '91707178-99e2-4585-b45c-a9fc9e253b21',
        title: "Maintaining a claims register\n(insulating glazing)",
        method: "Permanent instruction",
        record: "Existence of a register",
        userId: user.id
      }
    ]
  })


  console.log(`Database has been seeded. 🌱`);
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
